### ISSUE TITLE
Issue with example command

### ISSUE THREAD

**Issue by Vedaad-Shakib** [skirdey/voicerestore#5]
Hi,

I'm trying to run the example command (`python inference_short.py --checkpoint ./checkpoints/voice-restore-20d-16h-optim.pt --input test_input.wav --output test_output.wav --steps 32 --cfg_strength 0.5`), and I'm getting the following error. My environment is clean (Python 3.10), and I ran `pip install -r requirements.txt`, along with other dependencies that were missing from `requirements.txt`, like `pip install pyyaml`.

```
/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/nn/utils/weight_norm.py:134: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
Loading weights from nvidia/bigvgan_v2_24khz_100band_256x
/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/BigVGAN/bigvgan.py:482: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint_dict = torch.load(model_file, map_location=map_location)
Removing weight norm...
[WARNING] Min value of input waveform signal is -3.979588508605957
[WARNING] Max value of input waveform signal is 3.736807346343994
/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/inference_short.py:32: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state_dict = torch.load(save_path, map_location=torch.device(device))
/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/_inductor/lowering.py:1612: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager.
  warnings.warn(
Traceback (most recent call last):
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/inference_short.py", line 74, in <module>
    restore_audio(optimized_model, args.input, args.output, steps=args.steps, cfg_strength=args.cfg_strength)
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/inference_short.py", line 50, in restore_audio
    restored_wav = model(audio, steps=steps, cfg_strength=cfg_strength)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/model.py", line 43, in forward
    processed_mel = get_mel_spectrogram(audio, self.bigvgan_model.h).to(self.device)
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/model.py", line 46, in torch_dynamo_resume_in_forward_at_43
    restored_mel = self.voice_restore.sample(processed_mel.transpose(1, 2), steps=steps, cfg_strength=cfg_strength)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/voice_restore.py", line 229, in sample
    self.eval()
  File "/mnt/cr-shared/home/vedaadshakib/scratch/voicerestore/voice_restore.py", line 236, in torch_dynamo_resume_in_sample_at_229
    trajectory = odeint(ode_fn, y0, times, **self.odeint_kwargs)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torchdiffeq/_impl/odeint.py", line 74, in odeint
    shapes, func, y0, t, rtol, atol, method, options, event_fn, t_is_reversed = _check_inputs(func, y0, t, rtol, atol, method, options, event_fn, SOLVERS)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torchdiffeq/_impl/misc.py", line 268, in _check_inputs
    _check_timelike('t', t, True)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torchdiffeq/_impl/misc.py", line 268, in torch_dynamo_resume_in__check_inputs_at_268
    _check_timelike('t', t, True)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torchdiffeq/_impl/misc.py", line 296, in torch_dynamo_resume_in__check_inputs_at_270
    _assert_increasing('t', t)
  File "/home/vedaadshakib/.local/lib/python3.10/site-packages/torchdiffeq/_impl/misc.py", line 296, in torch_dynamo_resume_in__check_inputs_at_296
    _assert_increasing('t', t)
AttributeError: 'function' object has no attribute 'callback_step'
```

Any suggestions? It seems like a package version error, but my package versions match the ones provided in your `requirements.txt`.

**Comment by skirdey** [comment]
Hi Vedaad! Let me take a look today, I'll dig into why torchdiffeq throws
the callback error.

**Comment by skirdey** [comment]
I just pushed a small update that should fix the issue.

**Comment by Vedaad-Shakib** [comment]
Awesome, thank you!!
